#+hugo_base_dir: ../
#+OPTIONS: ^:nil
* Website
** DONE Index
   CLOSED: [2025-04-17 Thu 21:13]
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: /
   :EXPORT_FILE_NAME: _index
   :END:

   Welcome to my website! I am Aniket Mishra, currently pursuing my Bachelor of Technology in Computer Science at IIT Gandhinagar. I also currently lead @@hugo:[,\ AMBDA.]({{< relref "lambda/about">}})@@, a group/club in IIT Gandhinagar that is focussed on PL Theory and related fields. You can find my CV (along with other contact information) [[/moderncv.pdf][here]].
** DONE Miscellaneous
   CLOSED: [2025-04-21 Mon 11:55]
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: /
   :EXPORT_FILE_NAME: misc
   :END:
   Hello! Here are some miscellaneous things to look at.
*** Some Links to Click
    Here are some websites worth checking out.
    + *[[https://www.typetheoryforall.com/][Type Theory Forall]]* - A cool podcast on PLT and Type Theory.
    + *[[https://initiatives.iitgn.ac.in/nyasa/][Nyasa]]* - Volunteer Organisation in IIT Gandhinagar focussed on helping impoverished communities near the campus.
** BLOG-POSTS  :blogposts:
   :PROPERTIES:
   :CATEGORY: blog-posts
   :END:
*** DONE Hello World!
    CLOSED: [2025-04-17 Thu 21:13]
   :PROPERTIES:
   :EXPORT_FILE_NAME: hello-world
   :END:

   Hello, this is my first post upon migrating to Hugo for generating my site.
** DONE LAMBDA
   CLOSED: [2025-04-17 Thu 21:13]
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: /lambda
   :END:
*** DONE About ,\ AMBDA.
    CLOSED: [2025-04-17 Thu 21:13]
    :PROPERTIES:
    :EXPORT_FILE_NAME: about
    :END:

    [[/lambdalogo.svg]]
    
    ,\ AMBDA. is a hobby group in IIT Gandhinagar, which primarily deals with Programming Languages and related topics, with a focus on more of theoretical aspects. It was initiated through a proposal to the student senate of IITGN by me in October 2024. Our overarching goals are to -
    1. spread awareness of PLT and related topics on the IITGN campus.
    2. stay in touch with the current research in PLT and related fields.
    3. keep in touch with people working in PLs and related fields across India.
    4. conduct meaningful projects which should at the very least, advance the understanding of the students involved with them.

    We plan to move to Zulip from Whatsapp for our discussions, as it is better at supporting multithreaded conversations, and organising activities. Please join us [[https://lambda-iitgn.zulipchat.com/]] if you're interested! (PS: There's also a very convenient mobile app).

    Its current members are -
    * Aniket Mishra (That's me!)
    * [[mailto:jaskirat.maskeen@iitgn.ac.in][Jaskirat Singh Maskeen]]
    * [[mailto:23110040@iitgn.ac.in][Arjun B Dixit]]
    * [[mailto:gella.saikrishna@iitgn.ac.in][Gella Naga Sai Krishna]]
    * [[mailto:anvit.aggarwal@iitgn.ac.in][Anvit Aggrawal]]
    * [[mailto:neal.pineda@iitgn.ac.in][Neal Apte Pineda]]
    * [[mailto:tanish.yelgoe@iitgn.ac.in][Tanish Yelgoe]]

   If you want to check out the things we are working on/plan to work on, we track those things at [[https://github.com/satiscugcat/lambda-org][this github repo]]. If you'd like to reach out to us to collaborate, please do send an email!

      
    
    
   
